### PR TITLE
Handle hex binary data

### PR DESCRIPTION
**Pull request by madig**
As encountered in a Glyphs 2.5 file.

### CODE REVIEW

**Comment by anthrotype** [comment]
did you check this?
https://github.com/googlei18n/glyphsLib/issues/119

**Comment by madig** [comment]
Nope.

**Comment by anthrotype** [comment]
Basically we need to figure out from which Glyphs.app version the serialisation of the binary data changed from one format to the other and decode accordingly

**Comment by schriftgestalt** [comment]
Can you check how many file even have binary data? I suspect it to be none or only very few.

**Comment by madig** [comment]
One turned up the other day, it may have come from on of our FontLab scripts.

**Comment by schriftgestalt** [comment]
The change was in the 2.5 branch around build 995, but the build number is not really helping here as there where similar numbers in the 2.4 branch ;(. I don’t have a list of all 2.5 versions and their numbers.

**Comment by madig** [comment]
Hm. Merge PR as is then? Maybe not worth the effort to list all version numbers that may be affected?

**Comment by anthrotype** [comment]
maybe we should only support binary data encoded as hexadecimal string, and remove support for base64 encoded strings, now that Glyphs.app only writes it as hexadecimal.

**Comment by madig** [comment]
I just tried to access the binary data we found in one file, hex format. Neither 939 nor 1103 could access the data, both just ignore it. I also couldn't make any binary data from the macro window -- what would produce binary? 

So... Let's drop base64?

**Comment by anthrotype** [comment]
> Let's drop base64?

yeah. We never released a glyphsLib version which included support for it anyway.

**Comment by anthrotype** [comment]
I'm gonna remove base64 support

**Pull request merged**
