### PR TITLE
use 'fileName' customParameter for instance filenames

### PR DESCRIPTION
**Pull request by moyogo**

### CODE REVIEW

**Comment by anthrotype** [comment]
Is this a new built-in custom parameter?

**Comment by moyogo** [comment]
It’s in the 2.3 manual https://glyphsapp.com/downloads/handbook/Glyphs-Handbook-2.3.pdf#page=184

**Comment by schriftgestalt** [comment]
This parameter is at least four years old.

**Comment by anthrotype** [comment]
I was just asking :)

**Comment by moyogo** [comment]
OK. If that was the only question, I’ll merge then ;-).
3eefb4e broke the tests, changing the layer order.

**Comment by anthrotype** [comment]
lgtm

**Pull request merged**
