### PR TITLE
fix #457 Remove Glyphs

### LINKED ISSUE #457: How to del glyphs?
Looks like that's not currently possible?

```
 File "/usr/local/lib/python2.7/site-packages/glyphsLib/classes.py", line 610, in __delitem__
    raise KeyError  # TODO: add other access methods
```

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Can someone please have a look. I fixed my mistakes and now it complains about something I didn't touch.

**Comment by madig** [comment]
Dunno why it shows up now, but please add an `r` to the strings in those 2 locations (`re.compile(r"{{([-.e\d]+), ([-.e\d]+)}, {([-.e\d]+), ([-.e\d]+)}}")` and `r"\s*;\s*"`).

Also, please keep the `else: raise KeyError` in, then I can merge this.

**Comment by madig** [comment]
It does, but I'd like to add a test. Can you enable "maintainer edits" for this PR so I can write to this branch?

**Comment by schriftgestalt** [comment]
That option is set already

**Comment by madig** [comment]
I am so ok I even authored the commit.

**Pull request merged**
