### PR TITLE
[custom_params] cast xHeight value to int

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlei18n/glyphsLib/issues/268

### CODE REVIEW

**Comment by anthrotype** [comment]
we can't add "xHeight" to `GSCustomParameter._CUSTOM_INT_PARAMS` list, otherwise we can't roundtrip *.glyphs files that contain it (it would lose the quotes), so I think this is the only solution for now.
Merging.

**Comment by moyogo** [comment]
Coming back to this, I don't think we should support this custom parameter if it's not supported by Glyphs.app.

Currently those files have the Arabic xHeight defined as the font xHeight attribute and then redefine the non standard xHeight custom parameter in each instance with the same value.

The source files should be changed to have the correct font xHeight attribute, and use the fontMaster xHeight string to define the Arabic xHeight.

**Comment by anthrotype** [comment]
What is a “fontMaster xHeight string”?

**Comment by moyogo** [comment]
> What is a “fontMaster xHeight string”?

The fontMaster `xHeight` customParameter string; for example xHeight = "arabic: 325", that Glyphs.app uses to draw the xHeight on Arabic glyphs.

In NotoSansArabic-MM.glyphs, it seems the master.xHeight was used by designers to have the Arabic xHeight line drawn at 325. That is not the correct way to do it, at least not in the latest versions of Glyphs.app. Instead, use master.customParameters["xHeight"] = "arabic: 325". That will draw the xHeight line at 325 in the Arabic glyphs.
Then the master.xHeight can be what the xHeight should be in the final TTF, and the non official instance.customParameters["xHeight"] can be deleted since master.xHeight will have the right value.

The instance.customParameters["xHeight"] is not used by Glyphs.app, we shouldn’t use it either.

**Comment by moyogo** [comment]
See https://github.com/googlei18n/glyphsLib/issues/268#issuecomment-342292338

**Comment by anthrotype** [comment]
Thanks Denis for the clarification. Is this documented anywhere or we just have that comment from Georg?

**Pull request merged**
