### PR TITLE
Classtree cleanup

### PR DESCRIPTION
**Pull request by schriftgestalt**

### CODE REVIEW

**Comment by moyogo** [comment]
@googlebot I’m okay.

**Comment by schriftgestalt** [comment]
@moyogo Sorry for pulling it myself. But I just was in the mood of working on it a bit ;)

**Comment by schriftgestalt** [comment]
Thanks a lot.

**Comment by moyogo** [comment]
@schriftgestalt no problem :-) We should merge master in Class_new_tree since master has new commits. I have resolved the one conflict and updated the new tests that are in masters. I’ll open a PR now.

**Pull request merged**
