### PR TITLE
Normalize custom parameter names

### PR DESCRIPTION
**Pull request by jamesgk**
(Turns out this *is* necessary, I just hadn't done enough testing)

### CODE REVIEW

**Comment by schriftgestalt** [comment]
Can you send me the file where this happened? And where did the file come from?

**Comment by jamesgk** [comment]
For example: https://raw.githubusercontent.com/googlei18n/noto-source/master/src/NotoSansHebrew-MM.glyphs. The "Don't use Production Names" parameters use a curved apostrophe in Don't.

**Comment by schriftgestalt** [comment]
Please report this directly that I can fix it.

**Comment by schriftgestalt** [comment]
And it should only happen for custom parameters as that is the only place where the user can type.

**Comment by jamesgk** [comment]
> Please report this directly that I can fix it.

Sure, where should we report bugs directly to Glyphs?

> And it should only happen for custom parameters as that is the only place where the user can type.

Good to know, I'll update the comment.

**Comment by schriftgestalt** [comment]
> Sure, where should we report bugs directly to Glyphs?

The easiest is to send me an email.

> only place where the user can type.

I changed the configuration of the textfield and textview that it should not happen any more.

**Pull request merged**
