### PR TITLE
Generate the name of a master using family, width, weight, custom order

### PR DESCRIPTION
**Pull request by madig**
Fixes https://github.com/googlei18n/glyphsLib/issues/323.

### CODE REVIEW

**Comment by anthrotype** [comment]
does the `_splitName` function also need to be adjusted accordingly now that you changed the order returned by `_joinName`?

also, what does Glyphs.app when generating UFO masters? Does it write the width before the weight?

**Comment by madig** [comment]
Jany says that `_splitNames` does not expect order.

**Comment by anthrotype** [comment]
ok thanks. So was change this unintentional, or has something else changed in Glyphs.app recently?

**Comment by anthrotype** [comment]
> Jany says that _splitNames does not expect order.

perhaps for consistency with `_joinNames`, `_splitNames` should return the tuple as `(width, weight, custom)`

https://github.com/googlei18n/glyphsLib/pull/333/files#diff-2486ae3fe6d67c56b1c1b22402d779c1R1386

**Comment by anthrotype** [comment]
can we merge this?

**Comment by belluzj** [comment]
> So was this change unintentional, or has something else changed in Glyphs.app recently?

Unintentional, I was confused by the fact the elsewhere in the code, the weight is handled before the width, but didn't think of how the stylenames should look in the end.

> perhaps for consistency with _joinNames, _splitNames should return the tuple as (width, weight, custom)

Bof, I don't know, both those methods are supposed to be private so it does not really matter

> can we merge this?

Yes

**Pull request merged**
