### PR TITLE
Handle custom axes

### LINKED ISSUE #280: Use `Axes` property
There is a custom parameter `Axes`. It contains axis names and tags. It is required for variable font export and does limit the available coordinate fields in the master and instance settings.

### PR DESCRIPTION
**Pull request by belluzj**
Fix #280 and #158

* [x] Read-write the `Axes` parameter
* [x] Read-write the `Axis Location` parameter

This uses & replaces the work started in #306

### CODE REVIEW

**Comment by schriftgestalt** [comment]
You saw what I implemented that already and send a pull request?

**Comment by belluzj** [comment]
Yes, and I did use your ideas if not directly your code in this PR. However I want to make sure that what I understood is correct, hence the questions in #280

**Comment by belluzj** [comment]
With this branch, I was able to build a simple variable font with a custom axis using `fontmake -o variable -g Font.glyphs`. Maybe it can be tested on more complex fonts?

Also I haven't done anything with Virtual Masters, and I don't know what they're useful for. Maybe another PR can add support for those?

**Comment by belluzj** [comment]
@m4rc1e @davelab6 You said you were interested in this, right? Could you share the fonts with custom axes that you wanted to build? Or give it a try on your own and report any problems? Thanks in advance :)

**Comment by davelab6** [comment]
Marc please take a look

**Comment by anthrotype** [comment]
> I haven't done anything with Virtual Masters, and I don't know what they're useful for. Maybe another PR can add support for those?

yes, let's do that in a separate PR.

**Comment by belluzj** [comment]
I have tested this branch with the file transmitted by @m4rc1e, it does not fully build with fontmake because of https://github.com/googlei18n/fontmake/issues/411 but the glyphs -> designspace part seems to work. Here is the produced designspace (I removed the `com.schrifgestaltung` stuff for clarity):

```xml
<?xml version='1.0' encoding='utf-8'?>
<designspace format="3">
    <axes>
        <axis default="400" maximum="900" minimum="400" name="Weight" tag="wght">
            <labelname xml:lang="en">Weight</labelname>
            <map input="400" output="400" />
            <map input="900" output="900" />
        </axis>
    </axes>
    <sources>
        <source familyname="XXXX" filename="XXXX-Regular.ufo" name="XXXX Regular" stylename="Regular">
            <lib copy="1" />
            <groups copy="1" />
            <features copy="1" />
            <info copy="1" />
            <location>
                <dimension name="Weight" xvalue="400" />
            </location>
        </source>
        <source familyname="XXXX" filename="XXXX-Bold.ufo" name="XXXX Bold" stylename="Bold">
            <location>
                <dimension name="Weight" xvalue="900" />
            </location>
        </source>
    </sources>
    <instances>
        <instance familyname="XXXX" filename="../instance_ufo/XXXX-Regular.ufo" name="XXXX Regular" stylemapfamilyname="XXXX" stylemapstylename="regular" stylename="Regular">
            <location>
                <dimension name="Weight" xvalue="400" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="XXXX" filename="../instance_ufo/XXXX-Medium.ufo" name="XXXX Medium" stylemapfamilyname="XXXX Medium" stylemapstylename="regular" stylename="Medium">
            <location>
                <dimension name="Weight" xvalue="550" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="XXXX" filename="../instance_ufo/XXXX-Bold.ufo" name="XXXX Bold" stylemapfamilyname="XXXX" stylemapstylename="bold" stylename="Bold">
            <location>
                <dimension name="Weight" xvalue="750" />
            </location>
            <kerning />
            <info />
        </instance>
        <instance familyname="XXXX" filename="../instance_ufo/XXXX-Black.ufo" name="XXXX Black" stylemapfamilyname="XXXX Black" stylemapstylename="regular" stylename="Black">
            <location>
                <dimension name="Weight" xvalue="900" />
            </location>
            <kerning />
            <info />
        </instance>
    </instances>
</designspace>
```

**Comment by anthrotype** [comment]
@belluzj running fontmake tests with glyphsLib master raises this error, when attempting to generate the designspace axes for this file:

https://github.com/googlei18n/fontmake/blob/master/test/InterpolateLayoutTest/InterpolateLayoutTest.glyphs

> TypeError: '<=' not supported between instances of 'float' and 'NoneType'

https://travis-ci.org/googlei18n/fontmake/jobs/360259732#L516

Interestingly the error only happens on python3, on python2 it is silently doing the wrong thing.

**Comment by anthrotype** [comment]
@belluzj I just tried building `InterpolateLayoutTest.glyphs` with glyphsLib checked out to this #324 branch and it builds successfully. What about we merge this now to master, and do any cleanups in subsequent PRs?

**Comment by anthrotype** [comment]
`fontmake -i -m test/AvarDesignspaceTest.designspace` is failing with current glyphsLib master:

```
INFO:fontmake.font_project:Interpolating master UFOs from designspace
INFO:mutatorMath:	Generating instance MyFont-Regular.ufo
INFO:fontmake.font_project:Applying instance data from designspace
Traceback (most recent call last):
  File "/home/clupo/.pyenv/versions/fontmake-py36-stable/bin/fontmake", line 11, in <module>
    load_entry_point('fontmake', 'console_scripts', 'fontmake')()
  File "/home/clupo/Github/fontmake/Lib/fontmake/__main__.py", line 218, in main
    project.run_from_designspace(designspace_path, **args)
  File "/home/clupo/Github/fontmake/Lib/fontmake/font_project.py", line 470, in run_from_designspace
    include_filenames=filenames))
  File "/home/clupo/.pyenv/versions/3.6.3/envs/fontmake-py36-stable/src/glyphslib/Lib/glyphsLib/builder/instances.py", line 363, in apply_instance_data
    set_weight_class(ufo, designspace, designspace_instance)
  File "/home/clupo/.pyenv/versions/3.6.3/envs/fontmake-py36-stable/src/glyphslib/Lib/glyphsLib/builder/instances.py", line 307, in set_weight_class
    _set_class_from_instance(ufo, designspace, instance, WEIGHT_AXIS_DEF)
  File "/home/clupo/.pyenv/versions/3.6.3/envs/fontmake-py36-stable/src/glyphslib/Lib/glyphsLib/builder/instances.py", line 295, in _set_class_from_instance
    user_loc = interp(reverse_mapping, design_loc)
  File "/home/clupo/.pyenv/versions/3.6.3/envs/fontmake-py36-stable/src/glyphslib/Lib/glyphsLib/builder/axes.py", line 530, in interp
    if xa <= x <= xb:
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
```

https://travis-ci.org/googlei18n/fontmake/jobs/360580655#L516

**Comment by anthrotype** [comment]
hmm, by simply changing the axis name from lowercase "weight" to uppercase "Weight", then fontmake can build instances from the AvarDesignspaceTest.designspace test file:

https://github.com/googlei18n/fontmake/pull/410/commits/2ed6447f7b3b0c8941fac653f0c3f8fa7142798e

it appears as if glyphsLib is hardcoding these names somewhere, instead of looking at the axis element in the designspace.

this would become a problem once https://github.com/googlei18n/fontmake/pull/410 gets merged and all instances would receive `apply_instance_data` whether they came directly from a glyphs source, or indirectly from a designspace source (which may or may not be generated from glyphsLib).

**Comment by belluzj** [comment]
About "Weight" being hardcoded somewhere, it's totally possible, we're going to look into it. Is it OK to hardcode the axis tags wght, wdth instead, since those are standard?

About the width having the same values in t design locations and user locations, I think I got that from an existing test, but I'm not sure which one. Anyway I understand that at least with the new axis system in Glyphs, my assumption is wrong, so we'll remove it from the code (and see whether some test breaks)

**Pull request merged**
