### PR TITLE
Accept os.PathLike objects in GSFont.__init__

### PR DESCRIPTION
**Pull request by madig**
So you can pass in `Path` and friends.

### CODE REVIEW

**Comment by anthrotype** [comment]
got a test?
of course, if should `@pytest.mark.skipif(sys.version_info < (3,4)`

**Comment by madig** [comment]
Once we drop Python < 3.6, a better solution might be to copy the approach of the 3.6 stdlib: https://github.com/python/cpython/blob/a6a4dc816d68df04a7d592e0b6af8c7ecc4d4344/Lib/bz2.py#L91

**Comment by madig** [comment]
Anything missing?

**Comment by anthrotype** [comment]
I already approved, you can do the merge, no?

**Comment by madig** [comment]
I see no merge button :O

**Comment by anthrotype** [comment]
> I see no merge button :O

@madig sorry, I now added you as collaborator

**Pull request merged**
