### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by belluzj**

### CODE REVIEW

**Comment by belluzj** [comment]
Makes sense. Should I leave the main in the parser?

**Comment by anthrotype** [comment]
If it works, why not. ;)

**Comment by moyogo** [comment]
LGTM!

**Comment by moyogo** [comment]
@belluzj  Actually could you add the fix "if int(font.appVersion) < 895:" here as well, so we can merge it before ufo_roundtrip is done?

**Pull request merged**
