### PR TITLE
Fix Python 3 support

### LINKED ISSUE #56: Not yet Python3-ready?
While working on https://github.com/googlefonts/fontbakery/issues/754 I tried using glyphsLib with python 3.4 and got this crash:

```
felipe@guarana:~/devel/github_felipesanches/fontbakery$ ./fontbakery-fix-glyphs.py test3.glyphs 
Traceback (most recent call last):
  File "./fontbakery-fix-glyphs.py", line 17, in <module>
    import glyphsLib
  File "/usr/local/lib/python3.4/dist-packages/glyphsLib/__init__.py", line 25, in <module>
    from glyphsLib.parser import Parser
  File "/usr/local/lib/python3.4/dist-packages/glyphsLib/parser.py", line 119
    _unescape_re = re.compile(ur'(\\0[0-7]{2})|(\\U[0-9a-fA-F]{4,6})')
                                                                    ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by khaledhosny**
Fixes #56.

### CODE REVIEW

**Comment by anthrotype** [comment]
we must make sure that changing the data types of all strings does not produce any regressions. E.g. there are some stdlib modules that expect native `str` strings (bytes on py2, unicode on py3).

**Comment by anthrotype** [comment]
The tests pass on both python 2 and 3 on my local OS X machine (not sure how large is the coverage).

@khaledhosny since we now import `unicode_literals`, we no longer need the `u` in front of strings. Maybe you could strip the ones which are left.

```bash
$ git grep "\Wu[\'\"]"
Lib/glyphsLib/builder.py:351:        (u'\u2018', "'"), (u'\u2019', "'"), (u'\u201C', '"'), (u'\u201D', '"'))
Lib/glyphsLib/builder.py:724:    full_text = u'\n\n'.join([prefix_str, class_str, fea_str])
Lib/glyphsLib/builder_test.py:80:            {'name': u'‘bad’', 'value': 1},
Lib/glyphsLib/builder_test.py:81:            {'name': u'“also bad”', 'value': 2})}
Lib/glyphsLib/casting.py:59:    u'Don\u2019t use Production Names', 'DisableAllAutomaticBehaviour'))
Lib/glyphsLib/parser.py:210:    _escape_re = re.compile(u'([^\u0020-\u007e])|"')
```

**Comment by khaledhosny** [comment]
Done.

**Comment by anthrotype** [comment]
thanks Khaled!

**Pull request merged**
