### PR TITLE
Put UFO instances in instance_ufos/ subdirectory by default

### PR DESCRIPTION
**Pull request by madig**
[TestFont.zip](https://github.com/googlei18n/glyphsLib/files/1980923/TestFont.zip)
```
>>> import glyphsLib
>>> a=glyphsLib.load_to_ufos("TestFont.glyphs")
>>> a=glyphsLib.loads("TestFont.glyphs")
>>> d=glyphsLib.to_designspace(a)
>>> [x.filename for x in d.instances]
['instance_ufos/newFont-Regular.ufo', 'instance_ufos/newFont-Medium.ufo', 'instance_ufos/newFont-Bold.ufo']
>>> [x.filename for x in d.sources]
['newFont-Regular.ufo', 'newFont-Bold.ufo']
```

### CODE REVIEW

**Comment by anthrotype** [comment]
hm... so you're assuming fontmake's current defaults (which we are basically trying to get rid of).

**Comment by anthrotype** [comment]
note that the filename attributes are always relative to the directory of the designspace itself. Fontmake by default places the designspace in the same directory as the master_ufo, so the instance_ufo folder is actually a sibling `../instance_ufo`

**Comment by anthrotype** [comment]
anyway, I'm not sure this goes in the right direction. I'll have to think about it. Please give more info about the issue this is trying to solve, thanks.

**Comment by madig** [comment]
Well, the idea is to prevent instances overwriting masters if they have the same name. Where would this be better kept? Parameter in `to_designspace` or something?

**Comment by anthrotype** [comment]
this is related somewhat https://github.com/googlei18n/glyphsLib/issues/325

**Pull request closed without merging**
